#!/bin/bash 
echo "this automatic setting will guide you install php5, apache2, mysql for you"
sudo apt-get install mysql-server mysql-client apache2 php5 libapache2-mod-php5 \
php5-mysql php5-curl php5-gd php5-idn php-pear php5-imagick php5-imap php5-mcrypt \
php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite \
php5-tidy php5-xmlrpc php5-xsl mysql

echo ***************************
echo python mysqldb bag will be installed...
sudo apt-get python-dev libmysqlclient-dev
sudo wget http://sourceforge.net/projects/mysql-python/?source=dlp
tar  -zxvf  MySQL-python-1.2.4b4.tar.gz
cd MySQL-python-1.2.4b4
python setup.py install


